
# 使用官方 Python 3.12 作为基础镜像
# 使用pip命令安装ComfyUI的依赖
# 再将新的镜像作为基础镜像构建ComfyUI的镜像
FROM python:3.12-slim

# 设置工作目录
WORKDIR /app

# 只复制依赖文件
COPY ./src/requirements.txt .

# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt

# 这个基础镜像不需要暴露端口和启动命令